# GLOBAL STUFF
experiment_id: stage_c_3b_controlnet_identity
checkpoint_path: /path/to/checkpoint
output_path: /path/to/output
model_version: 3.6B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 256
image_size: 768
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 1
updates: 200000
backup_every: 2000
save_every: 1000
warmup_updates: 1
use_fsdp: True

# ControlNet specific
controlnet_bottleneck_mode: 'simple'
controlnet_blocks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
controlnet_filter: IdentityFilter
controlnet_filter_params: 
  max_faces: 4
  p_drop: 0.05
  p_full: 0.3
# offset_noise: 0.1

# CUSTOM CAPTIONS GETTER & FILTERS
captions_getter: ['txt', identity]
dataset_filters: 
  - ['width', 'lambda w: w >= 768']
  - ['height', 'lambda h: h >= 768']

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path:
  - s3://path/to/your/first/dataset/on/s3
  - s3://path/to/your/second/dataset/on/s3
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors